FROM ubuntu:22.04
RUN apt-get update && apt-get upgrade -y && apt-get install -fy && apt-get autoremove -y && apt-get autoclean && apt-get install -y nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
