FROM ubuntu:22.04
RUN apt-get update && apt-get upgrade -y && apt-get install -fy && apt-get autoremove -y && apt-get autoclean && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*
EXPOSE 80
COPY index.html /var/www/html/
CMD ["nginx", "-g", "daemon off;"]
WORKDIR /var/www/html
ENV APP_VERSION=1.0.0

