FROM ubuntu:22.04
LABEL maintainer="meuemail@emailprovider.com"
RUN apt-get update && apt-get upgrade -y && apt-get install -fy && apt-get autoremove -y && apt-get autoclean && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*
EXPOSE 80
COPY index.html /var/www/html/
WORKDIR /var/www/html
ENV APP_VERSION=1.0.0
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
