services:
  giropops-senhas:
    image: omarciodanilo/giropops-senhas-assinada:1.0
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
  redis:
    image: cgr.dev/chainguard/redis:latest
    ports:
      - "6379:6379"
    networks:
      - giropops

networks:
  giropops:
    driver: bridge
