services:
  giropops-senhas:
    build: . 
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    volumes:
      - strigus:/strigus
    deploy:
      resources:
        reservations:
          #cpus: "0.25"
          memory: "128M"
        limits:
          #cpus: "0.5"
          memory: "256M"
    depends_on:
      - redis

  redis:
    image: cgr.dev/chainguard/redis:latest
    networks:
      - giropops
    volumes:
      - strigus:/strigus
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  giropops:
    driver: bridge

volumes:
  strigus:
