FROM cgr.dev/chainguard/python:latest-dev AS dev

WORKDIR /app

RUN python -m venv venv
ENV PATH="/app/venv/bin":$PATH
COPY requirements.txt requirements.txt
ADD app.tar.gz .
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
